// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_secondScreen_screen_init(void)
{
ui_secondScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_secondScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_labelSwitchGreen = lv_btn_create(ui_secondScreen);
lv_obj_set_width( ui_labelSwitchGreen, 100);
lv_obj_set_height( ui_labelSwitchGreen, 100);
lv_obj_set_x( ui_labelSwitchGreen, -300 );
lv_obj_set_y( ui_labelSwitchGreen, -150 );
lv_obj_set_align( ui_labelSwitchGreen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_labelSwitchGreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_labelSwitchGreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_labelSwitchGreen, lv_color_hex(0x28AE54), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_labelSwitchGreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelBTNGreen = lv_label_create(ui_labelSwitchGreen);
lv_obj_set_width( ui_labelBTNGreen, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelBTNGreen, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelBTNGreen, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelBTNGreen,"SWITCH");
lv_obj_set_style_text_font(ui_labelBTNGreen, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_funcBTNGreen1 = lv_btn_create(ui_secondScreen);
lv_obj_set_width( ui_funcBTNGreen1, 100);
lv_obj_set_height( ui_funcBTNGreen1, 100);
lv_obj_set_x( ui_funcBTNGreen1, -150 );
lv_obj_set_y( ui_funcBTNGreen1, -150 );
lv_obj_set_align( ui_funcBTNGreen1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_funcBTNGreen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_funcBTNGreen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_funcBTNGreen1, lv_color_hex(0x28AE54), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_funcBTNGreen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_labelBTNGreen1 = lv_label_create(ui_funcBTNGreen1);
lv_obj_set_width( ui_labelBTNGreen1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_labelBTNGreen1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_labelBTNGreen1, LV_ALIGN_CENTER );
lv_label_set_text(ui_labelBTNGreen1,"FUNC 1");
lv_obj_set_style_text_font(ui_labelBTNGreen1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_labelSwitchGreen, ui_event_labelSwitchGreen, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_funcBTNGreen1, ui_event_funcBTNGreen1, LV_EVENT_ALL, NULL);

}
