// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_startup_screen_init(void)
{
ui_startup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_startup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_openControllerLabel = lv_label_create(ui_startup);
lv_obj_set_width( ui_openControllerLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_openControllerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_openControllerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_openControllerLabel,"Open Controller");
lv_obj_set_style_text_font(ui_openControllerLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_startup, ui_event_startup, LV_EVENT_ALL, NULL);

}
