// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_startup
void ui_startup_screen_init(void);
void ui_event_startup( lv_event_t * e);
lv_obj_t *ui_startup;
lv_obj_t *ui_openControllerLabel;
// CUSTOM VARIABLES


// SCREEN: ui_home
void ui_home_screen_init(void);
lv_obj_t *ui_home;
void ui_event_btnSwitchBlue( lv_event_t * e);
lv_obj_t *ui_btnSwitchBlue;
lv_obj_t *ui_labelBTNSwitch;
void ui_event_funcBTNBlue1( lv_event_t * e);
lv_obj_t *ui_funcBTNBlue1;
lv_obj_t *ui_labelBTNblue1;
void ui_event_Slider1( lv_event_t * e);
lv_obj_t *ui_Slider1;
lv_obj_t *ui_labelSliderBlue;
// CUSTOM VARIABLES
lv_obj_t *uic_labelSliderBlue;


// SCREEN: ui_secondScreen
void ui_secondScreen_screen_init(void);
lv_obj_t *ui_secondScreen;
void ui_event_labelSwitchGreen( lv_event_t * e);
lv_obj_t *ui_labelSwitchGreen;
lv_obj_t *ui_labelBTNGreen;
void ui_event_funcBTNGreen1( lv_event_t * e);
lv_obj_t *ui_funcBTNGreen1;
lv_obj_t *ui_labelBTNGreen1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_startup( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_home_screen_init);
}
}

void ui_event_btnSwitchBlue( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_secondScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_secondScreen_screen_init);
}
}

void ui_event_funcBTNBlue1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      funcBTNBlue1( e );
}
}

void ui_event_Slider1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_slider_set_text_value( ui_labelSliderBlue, target, "", "");
      sliderBlue( e );
}
}

void ui_event_labelSwitchGreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_home_screen_init);
}
}

void ui_event_funcBTNGreen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      funcBTNGreen1( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_startup_screen_init();
ui_home_screen_init();
ui_secondScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_startup);
}
