// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_startup
void ui_startup_screen_init(void);
void ui_event_startup( lv_event_t * e);
extern lv_obj_t *ui_startup;
extern lv_obj_t *ui_openControllerLabel;
// CUSTOM VARIABLES

// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t *ui_home;
void ui_event_btnSwitchBlue( lv_event_t * e);
extern lv_obj_t *ui_btnSwitchBlue;
extern lv_obj_t *ui_labelBTNSwitch;
void ui_event_funcBTNBlue1( lv_event_t * e);
extern lv_obj_t *ui_funcBTNBlue1;
extern lv_obj_t *ui_labelBTNblue1;
void ui_event_Slider1( lv_event_t * e);
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_labelSliderBlue;
// CUSTOM VARIABLES
extern lv_obj_t *uic_labelSliderBlue;

// SCREEN: ui_secondScreen
void ui_secondScreen_screen_init(void);
extern lv_obj_t *ui_secondScreen;
void ui_event_labelSwitchGreen( lv_event_t * e);
extern lv_obj_t *ui_labelSwitchGreen;
extern lv_obj_t *ui_labelBTNGreen;
void ui_event_funcBTNGreen1( lv_event_t * e);
extern lv_obj_t *ui_funcBTNGreen1;
extern lv_obj_t *ui_labelBTNGreen1;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
